// crates/ql-lsm/src/lib.rs
//
//! `ql-lsm` — kernel-side content-addressed exec enforcement (Linux, BPF-LSM).
//!
//! This is the kernel half of QuantmLayer's exec containment. It loads a
//! sleepable `BPF_LSM_CGROUP` program onto `bprm_check_security`, fills a hash
//! map with the approved SHA-256 digests from a [`Profile`]'s
//! [`ExecPolicy`](ql_profile::ExecPolicy), and attaches the program to a cell's
//! cgroup. From then on, any exec of a process in that cgroup whose binary's
//! content digest is not on the list is denied with `EPERM`. Deny-by-default.
//!
//! The BPF program itself ([`scripts/lsm-enforce/enforce.bpf.c`]) was validated
//! on real hardware before this wrapper existed; this crate is the loader.
//!
//! ## Scope
//!
//! This pins *which* binaries may execute, not what they do — interpreter
//! misuse is bounded by the seccomp / filesystem / network walls, not here.
//!
//! ## Platform
//!
//! Linux only, and only where `bpf` is an active LSM and IMA is available (see
//! `scripts/ql-kernel-probe.sh`). This crate is excluded from the workspace
//! because it needs the eBPF build toolchain; build it with
//! `cd crates/ql-lsm && cargo build`.

use std::cell::RefCell;
use std::mem::MaybeUninit;
use std::os::fd::RawFd;
use std::rc::Rc;

use ql_profile::{HashAlgo, Profile};

// The skeleton generated by build.rs from the validated enforce.bpf.c.
mod skel {
    #![allow(dead_code, non_snake_case, non_camel_case_types, clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/enforce.skel.rs"));
}
use skel::*;

use libbpf_rs::skel::{OpenSkel, SkelBuilder};
use libbpf_rs::{Link, MapCore as _, MapFlags, RingBufferBuilder};

/// `BPF_F_SLEEPABLE` from the BPF UAPI. `bpf_ima_file_hash` may sleep, so the
/// program must be loaded sleepable.
const BPF_F_SLEEPABLE: u32 = 1 << 4;

/// Errors from loading or attaching the exec enforcer.
#[derive(Debug, thiserror::Error)]
pub enum LsmError {
    /// A libbpf operation (open/load/map-update/attach) failed.
    #[error("BPF operation failed: {0}")]
    Bpf(#[from] libbpf_rs::Error),
    /// The profile has content-addressed exec enabled but no digests, which
    /// would deny every exec. Refuse rather than silently brick the cell.
    #[error("exec.enforce is set but allow_digests is empty")]
    NoDigests,
}

/// One exec decision observed at the kernel enforcement boundary, drained from
/// the BPF ring buffer. This is the userspace view of an `exec_event` the
/// `bprm_check_security` program emitted — ground truth of what actually tried
/// to run inside the cell and whether content-addressing let it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExecRecord {
    /// Wall-clock time of the exec, in milliseconds since the Unix epoch,
    /// derived from the kernel monotonic timestamp at drain time.
    pub ts_millis: u64,
    /// The binary's SHA-256 content digest (lowercase hex), or `None` if the
    /// kernel could not hash it (which is itself the deny reason).
    pub digest_hex: Option<String>,
    /// The thread-group id (pid) that performed the exec.
    pub pid: u32,
    /// The task comm (up to 15 bytes, NUL-trimmed).
    pub comm: String,
    /// Whether the exec was allowed (digest on the approved list).
    pub allowed: bool,
    /// The real parent's tgid at exec time, or `None` when the kernel could
    /// not supply it. Present so audit records can be grouped by the process
    /// that caused them — four isolated denials read very differently from
    /// four denials under one `npm install`. This is a parent link the kernel
    /// already knows, not inferred causality.
    pub ppid: Option<u32>,
}

/// Committed argv of one cell exec, captured post-commit by the
/// `sched_process_exec` BPF program and drained from the `argv_events` ring.
/// This is the *sound* committed copy (the immutable argv the new process sees,
/// not the racy pre-exec userspace copy), correlated to the exec's content
/// digest via the kernel `inflight` map.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArgvRecord {
    /// The exec's SHA-256 content digest (lowercase hex).
    pub digest_hex: String,
    /// The thread-group id (pid) that exec'd.
    pub pid: u32,
    /// The committed argv, split on NUL (as in `/proc/<pid>/cmdline`).
    pub argv: Vec<String>,
    /// `true` if a post-commit argv-deny rule matched and the kernel sent
    /// `SIGKILL` to this exec (Tier-1 detect-and-kill).
    pub killed: bool,
}

/// Wire size of `struct exec_event` in enforce.bpf.c: u64 ktime + digest[32] +
/// comm[16] + u32 pid + 2 flag bytes + 2 explicit pad + u32 ppid, tail-padded
/// to an 8-byte boundary.
const EVENT_SIZE: usize = 72;

/// Byte offset of `ppid` within `struct exec_event`. Named because the two
/// bytes before it were previously tail padding, so the offset is deliberate
/// rather than incidental.
const PPID_OFFSET: usize = 64;

/// SHA-256 digest length, mirroring `SHA256_LEN` in enforce.bpf.c.
const SHA256_LEN: usize = 32;
/// `ARGV_MAX` in enforce.bpf.c: bytes of committed argv captured per exec.
const ARGV_MAX: usize = 1024;
/// `ARGV_TOKEN_MAX` in enforce.bpf.c: width of one argv-deny token in the key.
const ARGV_TOKEN_MAX: usize = 32;
/// Header bytes of `struct argv_event` before the argv payload: digest[32] +
/// pid (u32) + len (u32) + killed (u8).
const ARGV_EVENT_HDR: usize = SHA256_LEN + 4 + 4 + 1;

/// Lowercase-hex encode without pulling in a formatting dependency.
fn hex(bytes: &[u8]) -> String {
    const H: &[u8; 16] = b"0123456789abcdef";
    let mut s = String::with_capacity(bytes.len() * 2);
    for &b in bytes {
        s.push(H[(b >> 4) as usize] as char);
        s.push(H[(b & 0x0f) as usize] as char);
    }
    s
}

/// The kernel monotonic clock (`CLOCK_MONOTONIC`), matching what
/// `bpf_ktime_get_ns` stamps into each event. In nanoseconds.
fn mono_now_ns() -> u64 {
    let mut ts = libc::timespec {
        tv_sec: 0,
        tv_nsec: 0,
    };
    // SAFETY: `ts` is a valid, writable timespec; clock_gettime only writes it.
    unsafe { libc::clock_gettime(libc::CLOCK_MONOTONIC, &mut ts) };
    let secs = ts.tv_sec as u64;
    let nsec = ts.tv_nsec as u64;
    secs.saturating_mul(1_000_000_000).saturating_add(nsec)
}

/// Wall-clock now, milliseconds since the Unix epoch.
fn wall_now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// Parse one `exec_event` from its raw ring-buffer bytes. Field offsets mirror
/// the C struct exactly; we read by offset rather than transmuting to avoid any
/// alignment assumptions. Native byte order — producer and consumer are the
/// same machine. The event's monotonic `ktime` is mapped to wall-clock using
/// the `mono_now_ns`/`wall_now_ms` reference captured at drain time.
fn parse_event(data: &[u8], mono_now_ns: u64, wall_now_ms: u64) -> Option<ExecRecord> {
    if data.len() < EVENT_SIZE {
        return None;
    }
    let ktime_ns = u64::from_ne_bytes(data[0..8].try_into().ok()?);
    let hashed = data[61] != 0;
    let digest_hex = hashed.then(|| hex(&data[8..40]));
    let comm_raw = &data[40..56];
    let end = comm_raw
        .iter()
        .position(|&b| b == 0)
        .unwrap_or(comm_raw.len());
    let comm = String::from_utf8_lossy(&comm_raw[..end]).into_owned();
    let pid = u32::from_ne_bytes(data[56..60].try_into().ok()?);
    let allowed = data[60] != 0;
    // 0 means the kernel could not read real_parent; report that as unknown
    // rather than as pid 0, which is a real (if unusual) tgid.
    let ppid = match u32::from_ne_bytes(data[PPID_OFFSET..PPID_OFFSET + 4].try_into().ok()?) {
        0 => None,
        v => Some(v),
    };
    // The event happened `mono_now_ns - ktime_ns` ago; subtract that from now.
    let ago_ms = mono_now_ns.saturating_sub(ktime_ns) / 1_000_000;
    let ts_millis = wall_now_ms.saturating_sub(ago_ms);
    Some(ExecRecord {
        ts_millis,
        digest_hex,
        pid,
        comm,
        allowed,
        ppid,
    })
}

/// Parse one `argv_event` from its raw ring-buffer bytes (layout mirrors the C
/// struct: digest[32], pid u32, len u32, then `len` argv bytes). The argv bytes
/// are NUL-separated as in `/proc/<pid>/cmdline`; the trailing terminator NUL is
/// dropped, interior empty args preserved.
fn parse_argv_event(data: &[u8]) -> Option<ArgvRecord> {
    if data.len() < ARGV_EVENT_HDR {
        return None;
    }
    let digest_hex = hex(&data[0..SHA256_LEN]);
    let pid = u32::from_ne_bytes(data[SHA256_LEN..SHA256_LEN + 4].try_into().ok()?);
    let len = u32::from_ne_bytes(data[SHA256_LEN + 4..SHA256_LEN + 8].try_into().ok()?) as usize;
    let killed = data[SHA256_LEN + 8] != 0;
    let avail = data.len() - ARGV_EVENT_HDR;
    let take = len.min(ARGV_MAX).min(avail);
    let mut argv: Vec<String> = data[ARGV_EVENT_HDR..ARGV_EVENT_HDR + take]
        .split(|&b| b == 0)
        .map(|s| String::from_utf8_lossy(s).into_owned())
        .collect();
    if argv.last().is_some_and(|s| s.is_empty()) {
        argv.pop();
    }
    Some(ArgvRecord {
        digest_hex,
        pid,
        argv,
        killed,
    })
}

/// Which process opened one TCP connection, keyed by the port the broker will
/// see at `accept()`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConnOwner {
    /// Network-namespace inode the connection was made in. Part of the key
    /// because source ports are unique only within a namespace.
    pub netns: u32,
    /// Source port, allocated by the time this was recorded.
    pub sport: u16,
    /// The process (thread-group id), not the thread.
    pub pid: u32,
    /// Its real parent's tgid.
    pub ppid: u32,
    /// The task comm.
    pub comm: String,
}

/// A live content-addressed exec enforcer attached to one cgroup.
///
/// Enforcement is active for as long as this value is alive; dropping it
/// detaches the program (the cgroup reverts to unrestricted exec).
pub struct ExecEnforcer {
    // Field order matters for drop: the links are torn down before the skel.
    _link: Link,
    _argv_link: Link,
    /// Egress-attribution links (IPv4 and IPv6); held so the programs stay
    /// attached for the life of the cell.
    _conn_link: Link,
    _conn_link6: Link,
    _skel: EnforceSkel<'static>,
}

impl ExecEnforcer {
    /// Load the enforcer, populate the allow-list from
    /// `profile.exec.allow_digests`, and attach it to the cgroup referred to by
    /// `cgroup_fd` (an open file descriptor for the cgroup v2 directory).
    ///
    /// Requires privileges to load BPF-LSM programs (CAP_BPF + CAP_MAC_ADMIN,
    /// in practice root) and a kernel with `bpf` in its active LSM stack.
    pub fn attach(profile: &Profile, cgroup_fd: RawFd) -> Result<Self, LsmError> {
        if profile.exec.allow_digests.is_empty() {
            return Err(LsmError::NoDigests);
        }

        // The OpenObject backing storage must outlive the skel. We give it a
        // 'static lifetime by leaking a single small box (one per enforcer,
        // which lives for the cell's lifetime). A self-referential holder could
        // avoid the leak later if it ever matters.
        let open_object: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
            Box::leak(Box::new(MaybeUninit::uninit()));

        let builder = EnforceSkelBuilder::default();
        let mut open_skel = builder.open(open_object)?;

        // API(libbpf-rs 0.24): `set_flags` returns `()`, not `Result`.
        open_skel.progs.enforce_exec.set_flags(BPF_F_SLEEPABLE);

        let skel = open_skel.load()?;

        // Fill the allow-list: key = 32-byte SHA-256 digest, value = 1 byte.
        let one = [1u8];
        for digest in &profile.exec.allow_digests {
            let key = digest.to_bytes();
            // API(libbpf-rs 0.24): map accessor + `update` (via the MapCore trait).
            skel.maps.allowlist.update(&key, &one, MapFlags::ANY)?;
        }

        // Fill the Tier-1 argv-deny map (single-token subset of profile.argv_deny):
        // each single-token `all_of` rule becomes one (digest, token) key. Rules
        // that cannot be represented in this fixed-size kernel map — multi-token
        // `all_of`, non-sha256 digests, empty or over-long tokens — are skipped;
        // the userspace/Tier-2 path covers the full policy. key = digest[32] +
        // token[ARGV_TOKEN_MAX] (NUL-padded), value = 1 byte.
        let mut key = [0u8; SHA256_LEN + ARGV_TOKEN_MAX];
        for rule in &profile.exec.argv_deny {
            if rule.digest.algo() != HashAlgo::Sha256 {
                continue;
            }
            let digest = rule.digest.to_bytes();
            for deny in &rule.deny {
                if deny.all_of.len() != 1 {
                    continue; // kernel subset enforces single-token rules only
                }
                let tok = deny.all_of[0].as_bytes();
                if tok.is_empty() || tok.len() >= ARGV_TOKEN_MAX {
                    continue;
                }
                key.fill(0);
                key[..SHA256_LEN].copy_from_slice(&digest);
                key[SHA256_LEN..SHA256_LEN + tok.len()].copy_from_slice(tok);
                skel.maps.argv_deny.update(&key, &one, MapFlags::ANY)?;
            }
        }

        // API(libbpf-rs 0.24): attach an lsm_cgroup program to a cgroup fd.
        let link = skel.progs.enforce_exec.attach_cgroup(cgroup_fd)?;

        // Attach the post-commit committed-argv reader. It is a system-wide
        // tracepoint (sched_process_exec), scoped to this cell at runtime by the
        // `inflight` map that the cgroup-attached enforce_exec populates.
        let argv_link = skel.progs.capture_argv.attach()?;

        // Attach the egress-attribution tracepoint. Like `capture_argv` this is
        // system-wide; unlike it, nothing scopes it to this cell in-kernel — the
        // netns in each key is what lets a consumer select its own cell's
        // connections. Attaching is explicit here: a program that loads but is
        // never attached compiles, verifies, and silently never fires.
        let conn_link = skel.progs.note_connect_owner.attach()?;
        let conn_link6 = skel.progs.note_connect_owner6.attach()?;

        Ok(ExecEnforcer {
            _link: link,
            _argv_link: argv_link,
            _conn_link: conn_link,
            _conn_link6: conn_link6,
            _skel: skel,
        })
    }

    /// Every connection the kernel attributed to a process, for verifying that
    /// the attribution hook works before anything consumes it.
    ///
    /// Step 1 of B9: read-only, deletes nothing, and no other code path depends
    /// on it. The broker join comes later, and only if this shows sane data.
    pub fn dump_conn_owners(&self) -> Result<Vec<ConnOwner>, LsmError> {
        let map = &self._skel.maps.conn_owners;
        let mut out = Vec::new();
        for key in map.keys() {
            let Some(val) = map.lookup(&key, libbpf_rs::MapFlags::ANY)? else {
                continue;
            };
            if key.len() < 6 || val.len() < 8 {
                continue;
            }
            let netns = u32::from_ne_bytes(key[0..4].try_into().unwrap_or_default());
            let sport = u16::from_ne_bytes(key[4..6].try_into().unwrap_or_default());
            let pid = u32::from_ne_bytes(val[0..4].try_into().unwrap_or_default());
            let ppid = u32::from_ne_bytes(val[4..8].try_into().unwrap_or_default());
            let comm = val
                .get(8..)
                .map(|b| {
                    String::from_utf8_lossy(b)
                        .trim_end_matches('\0')
                        .to_string()
                })
                .unwrap_or_default();
            out.push(ConnOwner {
                netns,
                sport,
                pid,
                ppid,
                comm,
            });
        }
        Ok(out)
    }

    /// The process that opened the connection using `sport`, excluding any
    /// entry in `exclude_netns`.
    ///
    /// Source ports are unique per network namespace among live connections,
    /// but this map is populated by a system-wide hook, so the same port can
    /// appear for several namespaces. Rather than requiring the caller to know
    /// the cell's namespace — which the broker, running on the far side of a
    /// veth, does not — it excludes its *own*: any entry sharing the broker's
    /// namespace is the broker's onward connection, not the client's.
    ///
    /// Returns `None` when nothing matches **or when more than one does**. An
    /// ambiguous port is reported as unattributed rather than resolved by
    /// guessing, which is the same discipline the process tree applies to
    /// connects it cannot place.
    pub fn lookup_conn_owner(
        &self,
        sport: u16,
        exclude_netns: u32,
    ) -> Result<Option<ConnOwner>, LsmError> {
        let mut found: Option<ConnOwner> = None;
        for owner in self.dump_conn_owners()? {
            if owner.sport != sport || owner.netns == exclude_netns {
                continue;
            }
            if found.is_some() {
                // Two live namespaces using the same port: not resolvable.
                return Ok(None);
            }
            found = Some(owner);
        }
        Ok(found)
    }

    /// Drain every exec decision the kernel has emitted so far, returning them
    /// oldest-first. The BPF program streams one event per exec of a task in the
    /// attached cgroup; call this after the workload has run (or periodically)
    /// to collect the ground-truth record of what executed and what was denied.
    ///
    /// Best-effort by construction: if the kernel ring filled (a very busy
    /// cell), the producer dropped the overflow rather than blocking execs, so
    /// this returns what the ring retained.
    pub fn drain_events(&self) -> Result<Vec<ExecRecord>, LsmError> {
        // Reference points captured once: every event's monotonic ktime is
        // mapped to wall-clock against these.
        let mono_now = mono_now_ns();
        let wall_now = wall_now_ms();

        let collected: Rc<RefCell<Vec<ExecRecord>>> = Rc::new(RefCell::new(Vec::new()));
        let sink = Rc::clone(&collected);

        let mut builder = RingBufferBuilder::new();
        // API(libbpf-rs 0.24): add(map, callback) registers a per-record
        // callback; the callback returns 0 to continue.
        builder.add(&self._skel.maps.events, move |data: &[u8]| {
            if let Some(rec) = parse_event(data, mono_now, wall_now) {
                sink.borrow_mut().push(rec);
            }
            0
        })?;
        let ring = builder.build()?;
        // consume() invokes the callback for all currently-available records.
        ring.consume()?;
        drop(ring); // release the borrow of the events map before unwrapping

        Ok(Rc::try_unwrap(collected)
            .expect("ring buffer dropped, so this is the sole Rc")
            .into_inner())
    }

    /// Drain the committed-argv records captured since the last drain, oldest
    /// first. Each corresponds to one allowed exec inside the cell; the argv is
    /// the sound post-commit copy (read from the new mm at `sched_process_exec`),
    /// correlated to the exec's content digest. Best-effort like `drain_events`:
    /// a full ring drops overflow rather than blocking execs.
    pub fn drain_argv(&self) -> Result<Vec<ArgvRecord>, LsmError> {
        let collected: Rc<RefCell<Vec<ArgvRecord>>> = Rc::new(RefCell::new(Vec::new()));
        let sink = Rc::clone(&collected);

        let mut builder = RingBufferBuilder::new();
        builder.add(&self._skel.maps.argv_events, move |data: &[u8]| {
            if let Some(rec) = parse_argv_event(data) {
                sink.borrow_mut().push(rec);
            }
            0
        })?;
        let ring = builder.build()?;
        ring.consume()?;
        drop(ring);

        Ok(Rc::try_unwrap(collected)
            .expect("ring buffer dropped, so this is the sole Rc")
            .into_inner())
    }
}

#[cfg(test)]
mod ppid_wire_tests {
    use super::*;

    /// The wire layout must match enforce.bpf.c exactly. `ppid` sits at 64,
    /// in what used to be tail padding, so the struct stays a multiple of 8.
    #[test]
    fn event_layout_matches_the_bpf_struct() {
        // ktime 0..8, digest 8..40, comm 40..56, pid 56..60, flags 60..62,
        // explicit pad 62..64, ppid 64..68, tail pad to 72.
        assert_eq!(PPID_OFFSET, 64);
        assert_eq!(EVENT_SIZE, 72);
        assert_eq!(EVENT_SIZE % 8, 0, "must stay 8-byte aligned");
        assert!(PPID_OFFSET + 4 <= EVENT_SIZE);
    }

    /// A zero ppid means the kernel could not read `real_parent`, and must be
    /// reported as unknown rather than as pid 0 — which is a real tgid, so
    /// conflating them would attribute events to the wrong process.
    #[test]
    fn zero_ppid_parses_as_unknown_not_as_pid_zero() {
        let mut buf = [0u8; EVENT_SIZE];
        buf[0..8].copy_from_slice(&1u64.to_ne_bytes()); // ktime
        buf[56..60].copy_from_slice(&4242u32.to_ne_bytes()); // pid
        buf[60] = 1; // allowed
        buf[61] = 1; // hashed
        // ppid left zero.
        let rec = parse_event(&buf, u64::MAX, u64::MAX).expect("parses");
        assert_eq!(rec.pid, 4242);
        assert_eq!(rec.ppid, None);

        buf[PPID_OFFSET..PPID_OFFSET + 4].copy_from_slice(&99u32.to_ne_bytes());
        let rec = parse_event(&buf, u64::MAX, u64::MAX).expect("parses");
        assert_eq!(rec.ppid, Some(99));
    }
}
