// crates/ql-lsm/src/lib.rs
//
//! `ql-lsm` — kernel-side content-addressed exec enforcement (Linux, BPF-LSM).
//!
//! This is the kernel half of QuantmLayer's exec containment. It loads a
//! sleepable `BPF_LSM_CGROUP` program onto `bprm_check_security`, fills a hash
//! map with the approved SHA-256 digests from a [`Profile`]'s
//! [`ExecPolicy`](ql_profile::ExecPolicy), and attaches the program to a cell's
//! cgroup. From then on, any exec of a process in that cgroup whose binary's
//! content digest is not on the list is denied with `EPERM`. Deny-by-default.
//!
//! The BPF program itself ([`scripts/lsm-enforce/enforce.bpf.c`]) was validated
//! on real hardware before this wrapper existed; this crate is the loader.
//!
//! ## Scope
//!
//! This pins *which* binaries may execute, not what they do — interpreter
//! misuse is bounded by the seccomp / filesystem / network walls, not here.
//!
//! ## Platform
//!
//! Linux only, and only where `bpf` is an active LSM and IMA is available (see
//! `scripts/ql-kernel-probe.sh`). This crate is excluded from the workspace
//! because it needs the eBPF build toolchain; build it with
//! `cd crates/ql-lsm && cargo build`.

use std::mem::MaybeUninit;
use std::os::fd::RawFd;

use ql_profile::Profile;

// The skeleton generated by build.rs from the validated enforce.bpf.c.
mod skel {
    #![allow(dead_code, non_snake_case, non_camel_case_types, clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/enforce.skel.rs"));
}
use skel::*;

use libbpf_rs::skel::{OpenSkel, SkelBuilder};
use libbpf_rs::{Link, MapCore as _, MapFlags};

/// `BPF_F_SLEEPABLE` from the BPF UAPI. `bpf_ima_file_hash` may sleep, so the
/// program must be loaded sleepable.
const BPF_F_SLEEPABLE: u32 = 1 << 4;

/// Errors from loading or attaching the exec enforcer.
#[derive(Debug, thiserror::Error)]
pub enum LsmError {
    /// A libbpf operation (open/load/map-update/attach) failed.
    #[error("BPF operation failed: {0}")]
    Bpf(#[from] libbpf_rs::Error),
    /// The profile has content-addressed exec enabled but no digests, which
    /// would deny every exec. Refuse rather than silently brick the cell.
    #[error("exec.enforce is set but allow_digests is empty")]
    NoDigests,
}

/// A live content-addressed exec enforcer attached to one cgroup.
///
/// Enforcement is active for as long as this value is alive; dropping it
/// detaches the program (the cgroup reverts to unrestricted exec).
pub struct ExecEnforcer {
    // Field order matters for drop: the link is torn down before the skel.
    _link: Link,
    _skel: EnforceSkel<'static>,
}

impl ExecEnforcer {
    /// Load the enforcer, populate the allow-list from
    /// `profile.exec.allow_digests`, and attach it to the cgroup referred to by
    /// `cgroup_fd` (an open file descriptor for the cgroup v2 directory).
    ///
    /// Requires privileges to load BPF-LSM programs (CAP_BPF + CAP_MAC_ADMIN,
    /// in practice root) and a kernel with `bpf` in its active LSM stack.
    pub fn attach(profile: &Profile, cgroup_fd: RawFd) -> Result<Self, LsmError> {
        if profile.exec.allow_digests.is_empty() {
            return Err(LsmError::NoDigests);
        }

        // The OpenObject backing storage must outlive the skel. We give it a
        // 'static lifetime by leaking a single small box (one per enforcer,
        // which lives for the cell's lifetime). A self-referential holder could
        // avoid the leak later if it ever matters.
        let open_object: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
            Box::leak(Box::new(MaybeUninit::uninit()));

        let builder = EnforceSkelBuilder::default();
        let mut open_skel = builder.open(open_object)?;

        // API(libbpf-rs 0.24): `set_flags` returns `()`, not `Result`.
        open_skel.progs.enforce_exec.set_flags(BPF_F_SLEEPABLE);

        let skel = open_skel.load()?;

        // Fill the allow-list: key = 32-byte SHA-256 digest, value = 1 byte.
        let one = [1u8];
        for digest in &profile.exec.allow_digests {
            let key = digest.to_bytes();
            // API(libbpf-rs 0.24): map accessor + `update` (via the MapCore trait).
            skel.maps.allowlist.update(&key, &one, MapFlags::ANY)?;
        }

        // API(libbpf-rs 0.24): attach an lsm_cgroup program to a cgroup fd.
        let link = skel.progs.enforce_exec.attach_cgroup(cgroup_fd)?;

        Ok(ExecEnforcer {
            _link: link,
            _skel: skel,
        })
    }
}
